### ISSUE TITLE
100% page height not covered

### ISSUE THREAD

**Issue by varundabke** [staaky/strip#7]
Please see live demo here: http://rohitkhanvilkr.zz.mu/rkf.html
 Click on the last image in the list to open top sliding lightbox. We expect it to occupy full height, but keeps some margin down. 
OS is Windows 8.1, Browser Chrome 43.0.23.
Screen shot attached.
![stripjs](https://cloud.githubusercontent.com/assets/8374300/8258153/5b812440-16d0-11e5-951e-6fdb7ac3b929.jpg)

**Comment by staaky** [comment]
No matter which side you open Strip from, it won't cover the entire screen if your content isn't large enough for that, this is by design.

From what you are expecting I guess you are looking for a classic lightbox instead. I recommend using Fresco, it does exactly what you need:

http://www.frescojs.com
